#!/usr/bin/env bash
set -eu

echo "Script: 20-remove-packages.sh"

echo " > Remove unused packages..."
apt-get -y purge firefox || true
apt-get -y purge rhythmbox || true
apt-get -y purge thunderbird || true
apt-get -y purge totem || true

# From the file: casper/filesystem.manifest-remove
echo " > Remove language packages (reduce iso size)..."
apt-get -y purge gnome-user-docs-de || true
apt-get -y purge gnome-user-docs-es || true
apt-get -y purge gnome-user-docs-fr || true
apt-get -y purge gnome-user-docs-it || true
#apt-get -y purge gnome-user-docs-pt || true
apt-get -y purge gnome-user-docs-ru || true
apt-get -y purge gnome-user-docs-zh-hans || true
apt-get -y purge hunspell-de-at-frami || true
apt-get -y purge hunspell-de-ch-frami || true
apt-get -y purge hunspell-de-de-frami || true
apt-get -y purge hunspell-en-au || true
apt-get -y purge hunspell-en-ca || true
apt-get -y purge hunspell-en-gb || true
apt-get -y purge hunspell-en-za || true
apt-get -y purge hunspell-es || true
apt-get -y purge hunspell-fr || true
apt-get -y purge hunspell-fr-classical || true
apt-get -y purge hunspell-it || true
#apt-get -y purge hunspell-pt-br || true
#apt-get -y purge hunspell-pt-pt || true
apt-get -y purge hunspell-ru || true
apt-get -y purge hyphen-de || true
apt-get -y purge hyphen-en-ca || true
apt-get -y purge hyphen-en-gb || true
#apt-get -y purge hyphen-en-us || true
apt-get -y purge hyphen-es || true
apt-get -y purge hyphen-fr || true
apt-get -y purge hyphen-it || true
#apt-get -y purge hyphen-pt-br || true
#apt-get -y purge hyphen-pt-pt || true
apt-get -y purge hyphen-ru || true
apt-get -y purge language-pack-de || true
apt-get -y purge language-pack-de-base || true
#apt-get -y purge language-pack-en || true
#apt-get -y purge language-pack-en-base || true
apt-get -y purge language-pack-es || true
apt-get -y purge language-pack-es-base || true
apt-get -y purge language-pack-fr || true
apt-get -y purge language-pack-fr-base || true
apt-get -y purge language-pack-gnome-de || true
apt-get -y purge language-pack-gnome-de-base || true
#apt-get -y purge language-pack-gnome-en || true
#apt-get -y purge language-pack-gnome-en-base || true
apt-get -y purge language-pack-gnome-es || true
apt-get -y purge language-pack-gnome-es-base || true
apt-get -y purge language-pack-gnome-fr || true
apt-get -y purge language-pack-gnome-fr-base || true
apt-get -y purge language-pack-gnome-it || true
apt-get -y purge language-pack-gnome-it-base || true
#apt-get -y purge language-pack-gnome-pt || true
#apt-get -y purge language-pack-gnome-pt-base || true
apt-get -y purge language-pack-gnome-ru || true
apt-get -y purge language-pack-gnome-ru-base || true
apt-get -y purge language-pack-gnome-zh-hans || true
apt-get -y purge language-pack-gnome-zh-hans-base || true
apt-get -y purge language-pack-it || true
apt-get -y purge language-pack-it-base || true
#apt-get -y purge language-pack-pt || true
#apt-get -y purge language-pack-pt-base || true
apt-get -y purge language-pack-ru || true
apt-get -y purge language-pack-ru-base || true
apt-get -y purge language-pack-zh-hans || true
apt-get -y purge language-pack-zh-hans-base || true
#apt-get -y purge libreoffice-help-common || true
apt-get -y purge libreoffice-help-de || true
apt-get -y purge libreoffice-help-en-gb || true
#apt-get -y purge libreoffice-help-en-us || true
apt-get -y purge libreoffice-help-es || true
apt-get -y purge libreoffice-help-fr || true
apt-get -y purge libreoffice-help-it || true
#apt-get -y purge libreoffice-help-pt || true
#apt-get -y purge libreoffice-help-pt-br || true
apt-get -y purge libreoffice-help-ru || true
apt-get -y purge libreoffice-help-zh-cn || true
apt-get -y purge libreoffice-help-zh-tw || true
apt-get -y purge libreoffice-l10n-de || true
apt-get -y purge libreoffice-l10n-en-gb || true
apt-get -y purge libreoffice-l10n-en-za || true
apt-get -y purge libreoffice-l10n-es || true
apt-get -y purge libreoffice-l10n-fr || true
apt-get -y purge libreoffice-l10n-it || true
#apt-get -y purge libreoffice-l10n-pt || true
#apt-get -y purge libreoffice-l10n-pt-br || true
apt-get -y purge libreoffice-l10n-ru || true
apt-get -y purge libreoffice-l10n-zh-cn || true
apt-get -y purge libreoffice-l10n-zh-tw || true
apt-get -y purge mythes-de || true
apt-get -y purge mythes-de-ch || true
apt-get -y purge mythes-en-au || true
#apt-get -y purge mythes-en-us || true
apt-get -y purge mythes-es || true
apt-get -y purge mythes-fr || true
apt-get -y purge mythes-it || true
#apt-get -y purge mythes-pt-pt || true
apt-get -y purge mythes-ru || true
#apt-get -y purge wbrazilian || true
#apt-get -y purge wbritish || true
apt-get -y purge wfrench || true
apt-get -y purge witalian || true
apt-get -y purge wngerman || true
apt-get -y purge wogerman || true
#apt-get -y purge wportuguese || true
apt-get -y purge wspanish || true
apt-get -y purge wswiss || true

echo " > Remove others packages..."
apt-get --purge autoremove
